# Generated by Django 3.0.5 on 2021-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210520_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='loction',
            new_name='hospital_name',
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
