# Generated by Django 3.0.5 on 2021-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20210520_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
