# Generated by Django 3.0.5 on 2021-05-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
            preserve_default=False,
        ),
    ]
