# Generated by Django 3.0.5 on 2021-06-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20210602_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Discharged', 'Discharged')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='OtherCharge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='daySpent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
    ]
